version: "3"

services:
  nginx:
    image: parkingzpot_nginx
    build:
        context: ./nginx/
        args:
            CONFIG_FILE: 'nginx.conf'
    restart: unless-stopped
    depends_on:
        - api
        - frontend
    networks:
        - parkingzpot
    ports:
        - '8080:80'

  db:
    image: parkingzpot_db
    restart: unless-stopped
    build:
      context: ./postgres/
    ports:
      - "5432:5432"
    networks:
      - parkingzpot

  api:
    image: parkingzpot_api
    build:
      context: ./server/
    networks:
      - parkingzpot
    working_dir: /server
    volumes:
      - ./server:/server
      - ~/.m2:/root/.m2
    command: mvn clean spring-boot:run
    depends_on:
        - db

  frontend:
    image: parkingzpot_frontend
    build:
      context: ./client/
    networks:
      - parkingzpot
    depends_on:
      - api
    volumes:
      - ./client/:/app/
      - node_modules:/app/node_modules

volumes:
  node_modules:

networks:
  parkingzpot:
    driver: bridge