version: "3"

services:
  nginx:
    image: parkingzpot_nginx
    restart: unless-stopped
    build:
        context: ./nginx/
        args:
            CONFIG_FILE: 'nginx.conf'
    depends_on:
        - server
        - client
    networks:
        - parkingzpot
    ports:
        - '8080:80'

  db:
    image: parkingzpot_db
    restart: unless-stopped
    build:
      context: ./postgres/
    networks:
      - parkingzpot

  server:
    image: parkingzpot_server
    restart: unless-stopped
    build:
      context: ./server/
    networks:
      - parkingzpot
    working_dir: /server
    volumes:
      - ./server:/server
      - ~/.m2:/root/.m2
    command: mvn clean spring-boot:run
    depends_on:
        - db

  client:
    image: parkingzpot_client
    restart: unless-stopped
    build:
      context: ./client/
    networks:
      - parkingzpot
    depends_on:
      - server
    volumes:
      - ./client/:/app/
      - node_modules:/app/node_modules

volumes:
  node_modules:

networks:
  parkingzpot:
    driver: bridge