export const USER_AUTHENTICATION = 'USER_AUTHENTICATION';
export const USER_REGISTRATION = 'USER_REGISTRATION';
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const USER_LOGOUT = 'USER_LOGOUT';